
services:
  # Traefik Reverse Proxy - Main entry point
  traefik:
    image: traefik:v2.9
    container_name: traefik  # Using your desired container name
    ports:
      - "80:80"    # HTTP traffic
      - "443:443"  # HTTPS traffic
      - "8081:8080" # Dashboard
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro    
      - ./traefik:/etc/traefik:ro       
    networks:
      app-network:
        ipv4_address: 172.28.0.10      
    dns:
      - 172.28.0.2
    extra_hosts:
      - "step-ca.local:172.28.0.30"
    
    environment:
      - STEPCA_URL=https://step-ca.local:8443
    restart: unless-stopped


  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.home2500.local`)"
      - "traefik.http.routers.whoami.tls=true"
    networks:
      app-network:
        ipv4_address: 172.28.0.11      
    dns:
      - 172.28.0.2

networks:
  app-network:
    external: true
