services:
  # Traefik Reverse Proxy - Main entry point
  traefik:
    build:
      context: .
      dockerfile: Dockerfile
    image: traefix
    container_name: traefik
    extra_hosts:
      - "vault.app-network:172.28.0.6"
      - "host.docker.internal:host-gateway"    
    ports:
      - "80:80" # HTTP traffic
      - "443:443" # HTTPS traffic
      #- "8081:8080" # Dashboard
      #- "8082:8082" # metrics
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/etc/traefik/certs:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config:/etc/traefik/config:ro
      #- ./traefik/acme.json:/etc/traefik/acme.json
    environment:
      - LEGO_CA_CERTIFICATES=/etc/traefik/certs/ca/ca-chain.pem
      # Se o Vault usa SSL auto-assinado para o endpoint ACME:
      - LEGO_INSECURE_REGISTRATION=true
      - TRAEFIK_NETWORK=app-network
      - DOCKER_API_VERSION=1.52
    command:
      - "--experimental.plugins.rewrite-body.moduleName=github.com/packruler/rewrite-body"
      - "--experimental.plugins.rewrite-body.version=v1.2.0"
      - "--log.level=INFO"    

    networks:
      app-network:
        ipv4_address: 172.28.0.11    

    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.service=api@internal"

  whoami:
    image: containous/whoami
    container_name: whoami
    networks:
      app-network:
        ipv4_address: 172.28.0.12
    
    restart: unless-stopped
    labels:
      - traefik.enable=true    

# Define custom networks with proper subnet and DNS configuration
networks:
  app-network:
    name: app-network
    external: true
    ipam:
      config:
        - subnet: 172.28.0.0/16
        - gateway: 172.28.0.1
