worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Redirect all HTTP traffic to HTTPS
    server {
        listen 80;
        server_name home2500.local;
        return 301 https://$host$request_uri;
    }

    # Serve content over HTTPS
    server {
        listen 443 ssl http2;
        server_name home2500.local;

        # SSL config (same as above)
        ssl_certificate /etc/nginx/certs/web-server.cert.pem;
        ssl_certificate_key /etc/nginx/certs/web-server.key.pem;
        ssl_trusted_certificate /etc/nginx/certs/intermediate-ca.cert.pem;

        location / {
            proxy_pass http://pihole:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect http://pihole/ https://$host/;
        }
    }
}