directives:
  child_src: "'self'"
  connect_src: "'self' blob: https://raw.githubusercontent.com/owncloud/awesome-ocis/ https://auth.home2500.local"
  default_src: "'none'"
  font_src: "'self' data:"
  frame_ancestors: "'none'"
  frame_src: "'self'"
  img_src: "'self' data: blob:"
  manifest_src: "'self'"
  media_src: "'self'"
  object_src: "'self' blob:"
  script_src: "'self' 'unsafe-inline' 'unsafe-eval'"
  style_src: "'self' 'unsafe-inline'"
  worker_src: "'self'"
