server:
    ###########################################################################
    # BASIC SETTINGS
    ###########################################################################
    cache-max-ttl: 86400
    cache-min-ttl: 3600
    directory: "/opt/unbound/etc/unbound"
    interface: 0.0.0.0@53
    username: "_unbound"

    rrset-roundrobin: yes
    # this setting. Experimental option.
    ratelimit: 1000

    ###########################################################################
    # LOGGING
    ###########################################################################
    log-local-actions: no
    log-queries: no
    log-replies: no
    log-servfail: no
    verbosity: 0

    ###########################################################################
    # PRIVACY SETTINGS
    ###########################################################################
    qname-minimisation: yes
    aggressive-nsec: yes

    ###########################################################################
    # SECURITY SETTINGS
    ###########################################################################
    access-control: 127.0.0.1/32 allow
    access-control: 10.0.0.0/8 allow
    access-control: 192.168.0.0/16 allow
    access-control: 172.16.0.0/12 allow

    auto-trust-anchor-file: "var/root.key"

    harden-algo-downgrade: yes
    harden-below-nxdomain: yes
    harden-dnssec-stripped: yes
    harden-glue: yes
    harden-large-queries: yes
    harden-short-bufsize: yes
    harden-unknown-additional: yes

    hide-identity: yes
    hide-version: yes

    ###########################################################################
    # PERFORMANCE SETTINGS
    ###########################################################################
    num-threads: 2
    msg-cache-slabs: 4
    rrset-cache-slabs: 4
    infra-cache-slabs: 4
    key-cache-slabs: 4

    rrset-cache-size: 100m
    msg-cache-size: 50m

    outgoing-range: 950
    num-queries-per-thread: 475

    so-reuseport: yes
    so-rcvbuf: 1m
    so-sndbuf: 1m

    minimal-responses: yes
    serve-expired: yes

    ###########################################################################
    # LOCAL ZONE
    ###########################################################################
    local-zone: "local." nodefault

    ###########################################################################
    # FORWARD ZONE
    ###########################################################################
    forward-zone:
        name: "home2500.local."
        forward-addr: 127.0.0.1@53
        forward-first: yes

remote-control:
    control-enable: no