services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      app-network:
        ipv4_address: 172.28.0.45
    dns: 172.28.0.2

    restart: unless-stopped      

volumes:
  portainer_data:

networks:
  app-network:
    external: true
