services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /mnt/ssd980/immich_data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      # BASE DE DADOS
      # Aqui usamos o nome do serviço Postgres e a senha injetada pelo teu script de secrets
      - DB_URL=postgresql://${DB_USER}:${DB_PASS}@authentik-db.$INTERNAL_DOMAIN:5432/${CLIENT_APP_DB_NAME}
      # REDIS
      - REDIS_HOSTNAME=authentik-redis.${INTERNAL_DOMAIN}
      - REDIS_PASSWORD=${REDIS_PASSWORD} # Immich usa a mesma variável
      - REDIS_DBINDEX=3

      # MACHINE LEARNING
      # Garante que o serviço de ML no docker-compose se chama 'immich-ml'
      - IMMICH_MACHINE_LEARNING_URL=http://immich-ml.$INTERNAL_DOMAIN:3003
      - IMMICH_OAUTH_ENABLED=true
      - IMMICH_OAUTH_ISSUER_URL=https://auth.home2500.local/application/o/fotos/
      - IMMICH_OAUTH_CLIENT_ID=${OIDC_ID}
      - IMMICH_OAUTH_CLIENT_SECRET=${OIDC_SECRET}
      - IMMICH_OAUTH_AUTO_LAUNCH=true
      - IMMICH_OAUTH_AUTO_REGISTER=true
      - IMMICH_OAUTH_SCOPE=openid email profile
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - 2283:2283
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.immich.rule=Host(`fotos.home2500.local`)'
      - 'traefik.http.routers.immich.entrypoints=websecure'
      - 'traefik.http.routers.immich.tls=true'
      # O Immich gerencia o login via OIDC nativo, então não precisa de ForwardAuth aqui!
      #- "traefik.http.routers.immich.middlewares=authentik@docker"
      #- "traefik.http.routers.immich.middlewares=authentik-sso@file,security-headers@file"
      #- "traefik.http.services.immich.loadbalancer.passhostheader=true"
      - 'traefik.http.services.immich.loadbalancer.server.port=2283'
    restart: always
    networks:
      - app-network

  immich-machine-learning:
    container_name: immich-ml
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - /mnt/ssd980/immich_model_cache:/cache
    restart: always
    networks:
      - app-network

networks:
  app-network:
    external: true
