services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    env_file:
      - .env
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      # Enable TLS
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: ldap.crt
      LDAP_TLS_KEY_FILENAME: ldap.key
      LDAP_TLS_CA_CRT_FILENAME: ca.crt
      LDAP_TLS_VERIFY_CLIENT: "try"
    ports:
      - "389:389"   # LDAP
      - "636:636"   # LDAPS      
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
      # Add certificates volume            
      - ./ldap/tls:/container/service/slapd/assets/certs
    networks:
      app-network:
        ipv4_address: 172.28.0.19 # Static IP for authelia
    dns: 172.28.0.2
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    env_file:
      - .env
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8086:443"
      - "8085:80"  # Access phpLDAPadmin on http://localhost:8080
    depends_on:
      - openldap
    networks:
      app-network:
        ipv4_address: 172.28.0.20 # Static IP for authelia
    restart: unless-stopped

  authelia:
    container_name: 'auth'
    image: 'docker.io/authelia/authelia:latest'
    restart: 'unless-stopped'
    env_file:
      - .env
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/secrets/STORAGE_PASSWORD'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/secrets/STORAGE_ENCRYPTION_KEY'
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      #AUTHELIA_API_KEY: ${AUTHELIA_API_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      TZ: UTC            
    
    volumes:
      - './data/authelia/config:/config' # lock config. do not share, going to explore docker exec authelia *arguments
      - './data/authelia/secrets:/secrets:ro'

    networks:
      app-network:
        ipv4_address: 172.28.0.15 # Static IP for authelia

    dns: 172.28.0.2

    depends_on:
      - postgres  ## this name seams to be elated with this file service name only
      - openldap  
  postgres:
    image: postgres:15
    container_name: postgresql
    env_file:
      - .env
    restart: 'unless-stopped'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    secrets:
      - postgres-password
      - postgres-excryption
    networks:
      - app-network

secrets:
  postgres-password:
    file: ./data/authelia/secrets/STORAGE_PASSWORD    
  postgres-excryption:  
    file: ./data/authelia/secrets/STORAGE_ENCRYPTION_KEY

networks:
  app-network:
    external: true
