[global]
    # Otimiza o uso de RAM para ajudar com o seu problema de Swap
    memory mode = save
    history = 3600

[plugin:proc]
    # Desativa os arquivos que geram os erros de "Illegal seek" em modo host
    /proc/net/dev = no
    /proc/net/sockstat = no
    /proc/net/sockstat6 = no
    /proc/net/netstat = no

[web]
    # This locks Netdata to the internal loopback interface only
    bind to = 0.0.0.0:19999

[health]
    enabled = yes
    # Set this to no to stop it from trying to run alarm-notify.sh
    run recipients-notification-plugin = no    