# ./traefik/config/_2-core-dynamic.yml
# /etc/traefik/config/_2-core-dynamic.yml
http:
  # ----------------------------------------------------------------
  # SERVICES (Ajusta as portas se necessário)
  # ----------------------------------------------------------------
  services:
    authentik-service:
      loadBalancer:
        servers:
          - url: 'http://authentik-server.app-network:9000'

    mailcrab-service:
      loadBalancer:
        servers:
          - url: 'http://mailcrab.app-network:1080'

    pihole-service:
      loadBalancer:
        servers:
          - url: 'http://192.168.1.67:8080'

    vault-service:
      loadBalancer:
        servers:
          - url: 'https://vault.app-network:443'

    ocis-service:
      loadBalancer:
        servers:
          - url: 'https://files.app-network:9200'
        serversTransport: ocis-insecure

    whoami-service:
      loadBalancer:
        servers:
          - url: 'http://whoami.app-network:80'

  ## home2500 certification objective
  serversTransports:
    vault-internal:
      rootCAs: ['/etc/traefik/certs/ca-chain.pem']
      serverName: 'vault.app-network'
      insecureSkipVerify: true
    ocis-insecure:
      insecureSkipVerify: true
    insecureTransport:
      insecureSkipVerify: true

  middlewares:
    security-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        customRequestHeaders:
          X-Forwarded-Proto: 'https'

    ocis-csp:
      headers:
        contentSecurityPolicy: |
          default-src 'self';
          script-src 'self' 'unsafe-inline' 'unsafe-eval';
          style-src 'self' 'unsafe-inline';
          img-src 'self' data: blob: https://auth.home2500.local;
          font-src 'self' data:;
          connect-src 'self' blob: https://auth.home2500.local http://auth.home2500.local https://raw.githubusercontent.com/owncloud/awesome-ocis/;
          frame-src 'self' https://auth.home2500.local http://auth.home2500.local;
          worker-src 'self';
