http:
  services:
    # phpldapadmin Service
    phpldapadmin:
      loadBalancer:
        servers:
          - url: 'http://phpldapadmin.app-workspace:80'

  routers:
    # phpldapadmin Router - PUBLIC (no auth required)
    phpldapadmin:
      rule: 'Host(`phpldapadmin.home2500.local`)'
      entryPoints: ['websecure']
      service: 'phpldapadmin'
      middlewares: ['public-default'] # This should show phpldapadmin without login
      tls: {}
