version: 1
## tpl: authentik/app/blueprints/CLIENT_APP_NAME--apply-proxy.yaml
## yaml: authentik/blueprints/home2500_backup--apply-proxy.yaml
metadata:
  name: Home2500 backup apply proxy
  slug: blueprint-home2500-backup-apply-proxy
  labels:
    Domain: "backup.home2500.local"
    
entries:  
  - model: authentik_providers_proxy.proxyprovider
    id: prov-backup
    identifiers:
      name: "backup-provider"
    attrs:
      internal_host: "http://backup.app-network:9898"
      external_host: "https://backup.home2500.local"
      mode: "forward_single"
      intercept_header_auth: true
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]

  - model: authentik_core.application
    id: app-backup
    identifiers:
      slug: "backup"
    attrs:
      name: "BackRest"
      provider: !KeyOf prov-backup
      group: "Ferramentas"
      meta_launch_url: "https://backup.home2500.local/"      
      meta_icon: "https://auth.home2500.local/static/dist/assets/icons/home2500-icon.svg"

  - model: authentik_policies.policybinding
    identifiers: { target: !KeyOf app-backup, group: !Find [authentik_core.group, [name, "Home-Admins"]] }
    attrs: { order: 0 }          
  - model: authentik_policies.policybinding
    identifiers: { target: !KeyOf app-backup, group: !Find [authentik_core.group, [name, "Home-Developers"]] }
    attrs: { order: 1 }      
