services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - "3002:3001" # Change 3001 to your preferred host port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./uptime-kuma-data:/app/data # Persistent storage for monitors/settings
    environment:
      - TZ=Europe/Lisbon # Optional: Set your timezone (e.g., for Portugal)
    networks:
      - app-network
    #labels:
    #  - "traefik.enable=true"
    restart: unless-stopped


networks:
  app-network:
    external: true
