ping: true

global:
  checknewversion: false
  sendanonymoususage: false


metrics:
  prometheus: 
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true

api:
  dashboard: true
  #insecure: true #true  # Set to false and add authentication in production

experimental:
  plugins:
    rewrite-body:
      moduleName: "github.com/packruler/rewrite-body"
      version: "v1.2.0"


entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "60s"
        writeTimeout: "60s"
        idleTimeout: "180s"

  # Keep metrics on an internal/non-standard port
  metrics:
    address: ":8082"


providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "app-network" 
  file:
    directory: "/etc/traefik/config"
    watch: true

# Logging e AccessLog mantêm-se...
log:
  level: DEBUG
accessLog: {}

# todo
# Certificate resolvers (using Vault)
# CORRECT Vault Certificate Resolver for Traefik v3.6.1
#certificatesResolvers:
#  vault:
#    acme:
#      caServer: "https://vault.app-network:443/v1/pki_int/acme/directory"
#      storage: "/etc/traefik/acme.json"
#      email: "admin@home2500.local"
#      httpChallenge:
#        entryPoint: web